import {RACING_CAMELS as racers,EDITIONS,rollsRemainingThisLeg,fractionString} from './games/camel-up/simulator.js';
import {VERSION,preset,validate,moveEditor,reorder,label,color,analyze,legEV} from './games/camel-up/plugin.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const clone=o=>structuredClone(o), pct=n=>(n*100).toFixed(1)+'%', esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const swatch=(c,e)=>`<span class="swatch" style="--camel:${color(c,e)}"></span>`;
const token=(c,e)=>`<span class="camel ${['White','Yellow','CrazyWhite'].includes(c)&&!(e==='crazy'&&c==='White')?'light':''} ${c.startsWith('Crazy')?'crazy':''}" style="--camel:${color(c,e)}">${c==='CrazyWhite'?'C·W':c==='CrazyBlack'?'C·B':label(c,e).slice(0,3)}</span>`;
let state=preset(),selected='Blue',history=[],result=null,worker=null,request=0,toastTimer,installPrompt;
let storageOK=true,saves=[],progress={answered:0,correct:0};
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}}
function write(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{storageOK=false;notice('Browser storage is unavailable or full. Export your scenario to keep a copy.',true);return false;}}
function notice(message,error=false){const el=$('#notice');el.textContent=message;el.className='notice'+(error?' error':'');el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,6500);}
try { const draft=read('boardwise.draft',null); if(draft)state=validate(draft); }catch{}
const rawSaves=read('boardwise.saves',[]);
if(Array.isArray(rawSaves))for(const x of rawSaves.slice(0,100)){try{saves.push({id:String(x.id),name:String(x.name).slice(0,70),date:String(x.date),state:validate(x.state)});}catch{}}
const rawProgress=read('boardwise.progress',null);if(rawProgress&&Number.isInteger(rawProgress.answered)&&rawProgress.answered>=0&&Number.isInteger(rawProgress.correct)&&rawProgress.correct>=0&&rawProgress.correct<=rawProgress.answered)progress=rawProgress;
function openView(id){if(!['live','academy','saved','about'].includes(id))return;$$('.view').forEach(x=>x.hidden=x.id!==id);$$('.nav').forEach(x=>{x.classList.toggle('active',x.dataset.view===id);if(x.dataset.view===id)x.setAttribute('aria-current','page');else x.removeAttribute('aria-current');});if(id==='saved')renderSaved();if(id==='academy')renderLesson();window.scrollTo({top:0});}
$$('[data-view]').forEach(b=>b.onclick=()=>openView(b.dataset.view));$$('[data-goto]').forEach(b=>b.onclick=()=>openView(b.dataset.goto));
function stop(){if(worker){worker.terminate();worker=null;}request++;$('#cancel').hidden=true;$('#calculate').disabled=false;$('#range').disabled=false;}
function invalidate(){stop();result=null;$('#results').hidden=true;$('#result-empty').hidden=false;$('#result-empty').innerHTML='<span class="empty-dice">⚄</span><h3>Ready for a fresh perspective?</h3><p>Calculate this position to see the current leg probabilities.</p>';$('#range-result').textContent='';}
function commit(next){try{next=validate(next);history.push(clone(state));if(history.length>50)history.shift();state=next;invalidate();write('boardwise.draft',state);render();}catch(e){notice(e.message,true);}}
function render(){
 $('#edition').value=state.edition;$('#crazy-direction').hidden=state.edition!=='crazy';
 if(!EDITIONS[state.edition].activeCamels.includes(selected))selected='Blue';
 $('#board').innerHTML=Array.from({length:16},(_,i)=>{const t=i+1,stack=Object.entries(state.positions).filter(([,p])=>p.tile===t).sort((a,b)=>b[1].stack-a[1].stack),effect=state.spectators[t];return `<button class="space ${t===16?'last':''} ${state.positions[selected].tile===t?'has-selected':''}" data-tile="${t}" aria-label="Space ${t}${stack.length?', top to bottom: '+stack.map(([c])=>label(c,state.edition)).join(', '):', empty'}${effect?', '+effect:''}"><span class="space-num">${String(t).padStart(2,'0')}</span>${effect?`<span class="tile-effect ${effect}">${effect==='oasis'?'+1':'−1'}<small>${effect==='oasis'?'OASIS':'MIRAGE'}</small></span>`:''}${stack.map(([c])=>token(c,state.edition)).join('')}</button>`;}).join('');
 $$('#board [data-tile]').forEach(b=>b.onclick=()=>{const tile=Number(b.dataset.tile),tool=$('#tool').value;if(tool==='camel'){const next=moveSafely(tile);if(next)commit(next);}else{const next=clone(state);if(tool==='erase')delete next.spectators[tile];else next.spectators[tile]=tool;commit(next);}});
 $('#camel-picker').innerHTML=EDITIONS[state.edition].activeCamels.map(c=>`<button class="camel-choice" data-camel="${c}" aria-pressed="${selected===c}">${swatch(c,state.edition)}${label(c,state.edition)}</button>`).join('');
 $$('#camel-picker button').forEach(b=>b.onclick=()=>{selected=b.dataset.camel;$('#tool').value='camel';render();});
 $('#editor-instruction').textContent=`${label(selected,state.edition)} selected · tap a space to place.`;
 const p=state.positions[selected],stackSize=Object.values(state.positions).filter(x=>x.tile===p.tile).length;
 $('#lower').disabled=p.stack===0;$('#raise').disabled=p.stack===stackSize-1;$('#undo').disabled=!history.length;
 $('#dice').innerHTML=EDITIONS[state.edition].dice.map(c=>`<button class="die" data-die="${c}" aria-pressed="${state.dice.includes(c)}"><span class="die-face" style="--camel:${c==='Gray'?'#777c75':color(c,state.edition)}">⚄</span>${c==='Gray'?'Grey':label(c,state.edition)}<span>${state.dice.includes(c)?'✓':'–'}</span></button>`).join('');
 $$('#dice button').forEach(b=>b.onclick=()=>{const next=clone(state),c=b.dataset.die;next.dice=next.dice.includes(c)?next.dice.filter(d=>d!==c):[...next.dice,c];commit(next);});
 const n=rollsRemainingThisLeg(state.edition,state.dice.length);$('#roll-count').textContent=n?`${n} roll${n===1?'':'s'} remaining this leg`:'Leg complete · use New leg to refill';
 $('#save-count').textContent=saves.length;
}
function moveSafely(tile){try{return moveEditor(state,selected,tile);}catch(e){notice(e.message,true);return null;}}
$('#raise').onclick=()=>commit(reorder(state,selected,1));$('#lower').onclick=()=>commit(reorder(state,selected,-1));
$('#undo').onclick=()=>{if(history.length){state=history.pop();invalidate();write('boardwise.draft',state);render();}};
$('#edition').onchange=e=>commit(preset('opening',e.target.value));
$$('[data-preset]').forEach(b=>b.onclick=()=>commit(preset(b.dataset.preset,state.edition)));
$('#refill').onclick=()=>{const next=clone(state);next.dice=[...EDITIONS[next.edition].dice];next.spectators={};commit(next);notice('New leg: dice refilled and spectator tiles cleared.');};
function run(type){
 stop();const id=request,snapshot=clone(state);$('#calculate').disabled=true;$('#range').disabled=true;$('#cancel').hidden=false;
 if(type==='leg'){$('#result-empty').hidden=false;$('#results').hidden=true;$('#result-empty').innerHTML='<span class="empty-dice">⚄</span><h3>Exploring every roll…</h3><p>You can cancel or edit the board at any time.</p>';}else $('#range-result').textContent='Searching game-end bounds…';
 try{worker=new Worker(new URL('./worker.js',import.meta.url),{type:'module'});worker.onmessage=({data})=>{if(data.id!==request)return;if(data.progress){$('#range-result').textContent=`Completed depth ${data.progress.depth} · ${data.progress.nodes.toLocaleString()} states explored…`;return;}stop();if(data.error){notice(data.error,true);if(type==='leg')invalidate();else $('#range-result').textContent='Calculation failed. Check your board and retry.';return;}if(type==='leg'){result=data.result;result.elapsed=data.elapsed;renderResults();}else renderRange(data.result);};worker.onerror=()=>{stop();if(type==='leg')invalidate();else $('#range-result').textContent='Calculation could not start.';notice('Calculation could not start. Reload the page and try again.',true);};worker.postMessage({id,type,state:snapshot});}catch(e){stop();notice('This browser could not start the calculation worker. Try a current browser over HTTPS.',true);}
}
$('#calculate').onclick=()=>run('leg');$('#range').onclick=()=>run('range');$('#cancel').onclick=()=>{invalidate();notice('Calculation cancelled.');};
function renderResults(){
 $('#result-empty').hidden=true;$('#results').hidden=false;
 result.rows.forEach(r=>r.ev=legEV(r.p,state.payouts[r.camel]));const sorted=[...result.rows].sort((a,b)=>b.p[0]-a.p[0]),top=sorted[0],tied=sorted.filter(r=>Math.abs(r.p[0]-top.p[0])<1e-12),best=[...result.rows].filter(r=>r.ev!==null).sort((a,b)=>b.ev-a.ev)[0];
 $('#results').innerHTML=`<div class="result-hero"><small>${result.rollsToMake?'MOST LIKELY TO LEAD':'LEG COMPLETE · CURRENT RANKING'}</small><strong>${tied.length>1?'Joint leaders':label(top.camel,state.edition)} <span style="font-size:23px">${pct(top.p[0])}</span></strong><p>${tied.length>1?tied.map(r=>label(r.camel,state.edition)).join(' / '):'Chance of first place at this leg’s end.'}</p></div>${sorted.map(r=>`<div class="result-row"><div class="result-line">${swatch(r.camel,state.edition)}${label(r.camel,state.edition)}<strong>${pct(r.p[0])}</strong></div><div class="bar" style="--camel:${color(r.camel,state.edition)}"><i style="width:${r.p[0]*100}%"></i></div><div class="result-stats"><span>2nd ${pct(r.p[1])} · last ${pct(r.p[4])}</span><span title="Exact fraction for first place">${fractionString(result.counts[r.camel][0],result.totalWeight)}</span></div></div>`).join('')}<details><summary class="text-btn">All five finishing positions</summary><div class="table-scroll"><table class="rank-table"><thead><tr><th>Camel</th>${[1,2,3,4,5].map(i=>`<th>${i}</th>`).join('')}</tr></thead><tbody>${result.rows.map(r=>`<tr><td>${label(r.camel,state.edition)}</td>${r.p.map(p=>`<td>${pct(p)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></details><h3 style="margin-bottom:7px;font-size:13px">What is the next ticket worth?</h3><p class="hint" style="margin-bottom:10px">Set each camel’s next available leg ticket. EV is expected game coins per ticket.</p><table class="bet-table"><thead><tr><th>Camel</th><th>Ticket</th><th>EV · coins</th></tr></thead><tbody>${result.rows.map(r=>`<tr><td>${label(r.camel,state.edition)}</td><td><select data-payout="${r.camel}" aria-label="${label(r.camel,state.edition)} next ticket">${[5,3,2,0].map(n=>`<option value="${n}" ${state.payouts[r.camel]===n?'selected':''}>${n||'None'}</option>`).join('')}</select></td><td class="ev ${r.ev>=0?'positive':'negative'}">${r.ev===null?'—':(r.ev>=0?'+':'')+r.ev.toFixed(2)}</td></tr>`).join('')}</tbody></table><p class="hint">${!result.rollsToMake?'Leg is complete; these are settlement values, not new bets.':best?`Highest ticket EV: ${label(best.camel,state.edition)} (${best.ev>=0?'+':''}${best.ev.toFixed(2)}). ${best.ev<0?'All available bets have negative EV.':''}`:'No tickets marked available.'} This compares tickets only, not every possible action.</p><p class="hint">${result.totalWeight.toLocaleString()} weighted outcomes · ${(result.elapsed/1000).toFixed(2)}s · fixed tiles</p><div class="result-actions"><button id="export-current" class="text-btn">Export scenario ↓</button><button id="share-current" class="text-btn">Copy scenario link ↗</button></div>`;
 $$('[data-payout]').forEach(el=>el.onchange=()=>{state.payouts[el.dataset.payout]=Number(el.value);write('boardwise.draft',state);renderResults();});$('#export-current').onclick=()=>download('BoardWise_scenario.json',{...state});$('#share-current').onclick=()=>copyLink(state);
}
function renderRange(r){const bound=(v,up)=>((up?Math.ceil(Math.max(0,Math.min(1,v))*10000):Math.floor(Math.max(0,Math.min(1,v))*10000))/100).toFixed(2);$('#range-result').innerHTML=`<p><strong>${r.complete?'Completed model envelope':'Unfinished outer bounds'}</strong> · depth ${r.reachedDepth} · ${(r.elapsedMs/1000).toFixed(2)}s · ${r.nodes.toLocaleString()} states</p><div class="table-scroll"><table class="range-table"><thead><tr><th>Camel</th>${['1st','2nd','3rd','4th','5th'].map(s=>`<th>${s}</th>`).join('')}</tr></thead><tbody>${racers.map(c=>`<tr><th>${label(c,state.edition)}</th>${r.ranges[c].map(v=>`<td>${r.complete?(v.low*100).toFixed(2):bound(v.low,false)}–${r.complete?(v.high*100).toFixed(2):bound(v.high,true)}%</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="hint">Endpoints across cells are not one probability distribution. ${r.complete?'Complete within this model to numerical tolerance; not a human-strategy forecast.':'Unresolved branches remain bounded by 0 and 1. Wider bounds mean the search has not resolved those possibilities.'}</p>`;}
function download(name,obj){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function copyLink(s){const url=new URL(location.href);url.hash='s='+encodeURIComponent(JSON.stringify(s));try{await navigator.clipboard.writeText(url.href);notice('Scenario link copied.');}catch{download('BoardWise_scenario.json',s);notice('Clipboard unavailable; downloaded the scenario instead.');}}
function importHash(){if(location.hash.startsWith('#s=')){try{if(location.hash.length>16000)throw Error('Scenario link is too large.');state=validate(JSON.parse(decodeURIComponent(location.hash.slice(3))));history=[];invalidate();render();write('boardwise.draft',state);openView('live');notice('Shared scenario loaded.');}catch(e){notice('Could not load scenario link: '+e.message,true);}}}
window.addEventListener('hashchange',importHash);
$('#save').onclick=()=>{$('#scenario-name').value='';$('#save-dialog').showModal();$('#scenario-name').focus();};$('#close-dialog').onclick=()=>$('#save-dialog').close();
$('#save-form').onsubmit=e=>{e.preventDefault();const name=$('#scenario-name').value.trim();if(!name){$('#scenario-name').setCustomValidity('Enter a name.');$('#scenario-name').reportValidity();return;}if(saves.length>=100){notice('100 scenario limit reached. Export and remove a scenario first.',true);return;}const entry={id:crypto.randomUUID(),name,date:new Date().toISOString(),state:clone(state)};const next=[entry,...saves];if(write('boardwise.saves',next)){saves=next;$('#save-dialog').close();render();notice('Scenario saved on this device.');}};$('#scenario-name').oninput=e=>e.target.setCustomValidity('');
function renderSaved(){const list=$('#saved-list');if(!saves.length){list.innerHTML='<div class="empty"><h3>Your playbook starts here.</h3><p>Save a board from Live Assistant, or import a scenario JSON file.</p></div>';return;}list.innerHTML=saves.map((x,i)=>`<article class="saved-row"><div><h3>${esc(x.name)}</h3><p>${x.state.edition==='crazy'?'Second edition':'Classic'} · ${esc(new Date(x.date).toLocaleDateString())}</p></div><div class="saved-actions"><button class="btn small" data-load="${i}">Open</button><button class="btn small" data-export="${i}">Export</button><button class="btn small" data-share="${i}">Link</button><button class="btn small" data-remove="${i}" aria-label="Remove ${esc(x.name)}">Remove</button></div></article>`).join('');$$('[data-load]').forEach(b=>b.onclick=()=>{commit(clone(saves[Number(b.dataset.load)].state));openView('live');});$$('[data-export]').forEach(b=>b.onclick=()=>download('BoardWise_scenario.json',saves[Number(b.dataset.export)].state));$$('[data-share]').forEach(b=>b.onclick=()=>copyLink(saves[Number(b.dataset.share)].state));$$('[data-remove]').forEach(b=>b.onclick=()=>{if(b.dataset.confirm!=='yes'){b.dataset.confirm='yes';b.textContent='Confirm remove';return;}const next=saves.filter((_,i)=>i!==Number(b.dataset.remove));if(write('boardwise.saves',next)){saves=next;renderSaved();$('#save-count').textContent=saves.length;}});}
$('#import').onclick=()=>$('#import-file').click();$('#import-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>20000)throw Error('File exceeds the 20 KB scenario limit.');const next=validate(JSON.parse(await f.text()));commit(next);openView('live');notice('Scenario imported. Use Save scenario to keep it.');}catch(err){notice('Import failed: '+err.message,true);}finally{e.target.value='';}};
const lessons=[
 {name:'The passenger has an advantage',intro:'Blue is below Green on space 6. Only Blue’s die remains. All other camels are behind.',positions:[[6,0],[6,1],[3,0],[2,0],[1,0]],dice:['Blue'],explain:'When Blue moves, it carries Green. Green stays above Blue and therefore leads for all three possible faces.'},
 {name:'One roll, three possibilities',intro:'Green leads on space 8; Blue sits on space 6. Blue has the only remaining die.',positions:[[6,0],[8,0],[3,0],[2,0],[1,0]],dice:['Blue'],explain:'A 1 leaves Blue behind. A 2 lands Blue on top of Green; a 3 passes Green. Blue leads in two of the three equally likely outcomes.'},
 {name:'The finish changes everything',intro:'Blue is on space 16, Green on 15. Both dice remain. The first finish-line crossing ends the race.',positions:[[16,0],[15,0],[10,0],[9,0],[8,0]],dice:['Blue','Green'],explain:'If Blue rolls first, Blue wins. If Green rolls first, it either passes Blue or lands on top and is carried over. Each die is equally likely to come first, so Blue and Green tie at 50%.'},
 {name:'A mirage can undo a lead',intro:'Only Blue’s die remains. A mirage sits on space 9, just beyond Green.',positions:[[6,0],[8,0],[3,0],[2,0],[1,0]],dice:['Blue'],spectators:{9:'mirage'},explain:'A 1 leaves Blue behind; a 2 puts Blue on top of Green. A 3 hits the mirage and moves Blue underneath Green. Green leads in two of three outcomes.'}
];
let lessonIndex=0,lessonAnswered=false,lessonState,lessonAnalysis;
function renderLesson(){const l=lessons[lessonIndex];lessonState=preset();lessonState.positions=Object.fromEntries(racers.map((c,i)=>[c,{tile:l.positions[i][0],stack:l.positions[i][1]}]));lessonState.dice=[...l.dice];lessonState.spectators={...l.spectators};lessonAnalysis=analyze(lessonState);lessonAnswered=false;$('#lesson-number').textContent=`EXERCISE ${lessonIndex+1} / ${lessons.length}`;$('#lesson-title').textContent=l.name;$('#lesson-text').textContent=l.intro;$('#score').textContent=`${progress.correct} / ${progress.answered} CORRECT`;
 const tiles=[...new Set(Object.values(lessonState.positions).map(p=>p.tile).concat(Object.keys(lessonState.spectators).map(Number)))].sort((a,b)=>a-b);$('#lesson-board').innerHTML=tiles.map(t=>`<div class="lesson-space"><small>Space ${t}</small>${Object.entries(lessonState.positions).filter(([,p])=>p.tile===t).sort((a,b)=>b[1].stack-a[1].stack).map(([c])=>`<span>${label(c)}</span>${token(c,'classic')}`).join('')}${lessonState.spectators[t]?'<span>−1</span>':''}</div>`).join('');$('#lesson-dice').textContent=`Remaining dice: ${l.dice.join(', ')} · stacks shown top to bottom`;
 $('#answers').innerHTML=[...racers,'Tie'].map(c=>`<button class="btn" data-answer="${c}">${c==='Tie'?'Tie for highest':label(c)}</button>`).join('');$('#lesson-result').innerHTML='';$('#next-lesson').hidden=true;$$('[data-answer]').forEach(b=>b.onclick=()=>answerLesson(b.dataset.answer));}
function answerLesson(chosen){if(lessonAnswered)return;lessonAnswered=true;const max=Math.max(...lessonAnalysis.rows.map(r=>r.p[0])),leaders=lessonAnalysis.rows.filter(r=>Math.abs(r.p[0]-max)<1e-12),answer=leaders.length>1?'Tie':leaders[0].camel,correct=chosen===answer;progress.answered++;if(correct)progress.correct++;write('boardwise.progress',progress);$('#score').textContent=`${progress.correct} / ${progress.answered} CORRECT`;$$('[data-answer]').forEach(b=>{b.disabled=true;if(b.dataset.answer===answer)b.classList.add('primary');});$('#lesson-result').innerHTML=`<div class="lesson-feedback"><strong>${correct?'Correct.':'Here’s what the dice tell us.'}</strong><p>${lessons[lessonIndex].explain}</p><p>${lessonAnalysis.rows.map(r=>`${label(r.camel)} ${pct(r.p[0])}`).join(' · ')}</p><small>Computed with the same exact engine as Live Assistant.</small></div>`;$('#next-lesson').hidden=false;}
$('#next-lesson').onclick=()=>{lessonIndex=(lessonIndex+1)%lessons.length;renderLesson();};
$('#report').onclick=()=>{download('BoardWise_test_report.json',{version:VERSION,date:new Date().toISOString(),notes:$('#feedback').value,browser:navigator.userAgent,viewport:{width:innerWidth,height:innerHeight},scenario:state,legResult:result});notice('Test report downloaded. Share it with your feedback.');};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#install').hidden=false;});$('#install').onclick=async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null;$('#install').hidden=true;}};
render();importHash();
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').then(()=>navigator.serviceWorker.ready).then(()=>$('#offline-status').textContent='Offline files are ready. You can reopen this app without a connection.').catch(()=>$('#offline-status').textContent='Offline caching unavailable; the app still works while online.');}else $('#offline-status').textContent='This browser does not support offline caching.';
